accounts/urls.py
from django.urls import re_path
from . import views
from django.contrib.auth.views import (
        PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView, LoginView
        )
from django.contrib.auth.models import User
app_name = 'accounts'




urlpatterns = [
        re_path(r'^$', views.home, name="home"),
        re_path(r'^login/$', views.login_view, name="login"),
        re_path(r'^logout/$', views.logout_view, name="logout"),
        re_path(r'^signup/$', views.signup_view, name="signup"),
        re_path(r'^setting/(?P<username>\w+)/$', views.settings_view, name="settings"),
        re_path(r'^delete_confirm/$', views.delete_view, name="delete"),
        re_path(r'^delete/$', views.delete_account, name="delete_account"),
        re_path(r'^signup/details/$', views.signup_detailsview, name="details"),
        re_path(r'^profile/(?P<username>\w+)/$', views.view_profile, name="profile"),
        #re_path(r'^profile/(?P<username>\w+)/$', views.view_other, name="others_profile"),
        re_path(r'^profile/edit/(?P<username>\w+)/$', views.edit_profile, name="edit_profile"),
        re_path(r'^change-password/$', views.change_password, name="change_password"),
        re_path(r'^reset-password/$', PasswordResetView.as_view(template_name='accounts/reset_password.html', email_template_name="accounts/reset_password_email.html", success_url="done/"), name="password_reset"),
        re_path(r'^reset-password/done/$', PasswordResetDoneView.as_view(template_name='accounts/reset_password_done.html'), name="password_reset_done"),
        re_path(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', PasswordResetConfirmView.as_view(template_name="accounts/reset_password_confirm.html"), name="password_reset_confirm"),
        #path('reset/done', PasswordResetCompleteView.as_view(template_name="accounts/reset_password_complete.html"), name="password_reset_complete"),
        re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate, name='activate'),
]

api/urls.py
from django.urls import path,include,re_path
from api import views
from rest_framework.authtoken import views as authviews
urlpatterns = [
    path('userprofile',views.userprofile,name='userprofile'),
    path('testview',views.testview,name='testview'),
    path('interests',views.interests,name='interests'),
    path('friends',views.friends,name='friends'),
    path('friendrequest',views.friendrequest,name='friendrequest'),
    path('message',views.message,name='message'),
    path('forums',views.forums,name='forums'),
    path('topics',views.topics,name='topics'),
    path('posts',views.posts,name='posts'),
    path('polls',views.polls,name='polls'),
    path('vote',views.vote,name='vote'),
    re_path(r'^api-token-auth/', authviews.obtain_auth_token)
]

chat/urls.py
# chat/urls.py
from django.urls import path,re_path,include

from . import views
app_name="chat"
urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^(?P<room_name>[^/]+)/$', views.room, name='room'),
    
]

circlr/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from accounts import views as accounts_views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import PasswordResetCompleteView

urlpatterns = [
	path('reset/done/', PasswordResetCompleteView.as_view(template_name="accounts/reset_password_complete.html"), name="password_reset_complete"),
    path('admin/', admin.site.urls),
	path('api/',include('api.urls')),
    re_path(r'^accounts/', include('accounts.urls', namespace='accounts')),
    re_path(r'^$', accounts_views.home, name="home"),
    path('', include('django.contrib.auth.urls')),
    path('forums/', include('forums.urls')),
	path('friends/', include('friends.urls'), name="friends"),
    path('polls/', include('polls.urls')),
	re_path(r'^files/', include('files.urls')),
    re_path(r'^chat/', include('chat.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

friends/urls.py
from django.urls import path, include, re_path
# from django.conf.urls import url
from . import views

urlpatterns=[
    
    path('matching/',views.matching,name='matching'),
    path('sendr/',views.sendr,name='sendr'),
    path('acceptr/',views.acceptr,name='acceptr'),
    path('decliner/',views.decliner,name='decliner'),
    path('accounts/profile/<str:username>', views.view_profile, name="profile"),
]

polls/urls.py
from django.urls import path

from . import views
app_name = "polls"
urlpatterns = [
    path('',views.index,name="index"),
    path('<int:question_id>/', views.detail, name="detail"),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name="vote"),
    path('questions/', views.questions , name='questions'),
    path('choices/', views.choices, name='choices'),
    path('savechoices/', views.savechoices, name='savechoices'),

]

chat/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Message(models.Model):
    sender = models.ForeignKey(User,on_delete = models.CASCADE,related_name="tosender")
    receiver = models.ForeignKey(User,on_delete = models.CASCADE,related_name="toreceiver",default = 1)
    roomname = models.CharField(max_length = 100)
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now=True)

chat/views.py
# chat/views.py
from django.shortcuts import render
from django.utils.safestring import mark_safe
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from accounts.models import UserProfile
import json
from django.views.decorators.csrf import csrf_exempt
from .logger import *
from .validator import *

@login_required(login_url='/accounts/login/')
def index(request):
    recentlist = get_recents(request.user.username)
    return render(request, 'chat/index.html', {
        'userlist' : User.objects.all(),
        'recentlist':recentlist
    })

@login_required(login_url='/accounts/login/')
def room(request, room_name):
    if roomvalidate(request.user.username,room_name):
        recentlist = get_recents(request.user.username)
        print(recentlist)
        return render(request, 'chat/chatroom.html', {
            'room_name_json': mark_safe(json.dumps(room_name)),
            'message_log':load_log(room_name),
            'userlist' : User.objects.all(),
            'recentlist':recentlist
            })
    else:
        return render(request,'chat/linkbroken.html',{})

chat/templates/chat/index.html
<html>
<head>
    <title>Chat</title>
{% load static %}
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
	<style type="text/css" media="screen">
		pre {
			font-family: Verdana, "Bitstream Vera Sans", Geneva, sans-serif;
		}
  </style>
  <link id="favicon" rel="icon" href="{% static 'favicon.ico' %}">
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" type="text/css" rel="stylesheet">
<script src="{% static 'js/main.js' %}"></script>
  {% load static %}
<link rel="stylesheet" href="{% static "chat/chatcss.css" %}" >
<link rel="stylesheet" href="{% static 'css/main-cpy.css' %}">
<style>
	@font-face {
    font-family: Sitefont-book;
    src: url({% static '/fonts/book.otf' %});
}

@font-face {
    font-family: Sitefont-Medium;
    src: url({% static '/fonts/medium.otf'%});
}
</style>
</head>
<body>
    <div class="navbarcont" id="navbarcont">
        <nav class="navbr" id="navbar">
          <input type="checkbox" id="nav" class="hidden">
          <label for="nav" class="nav-btn">
            <i></i>
            <i></i>
            <i></i>
          </label>
          <div class="logo">
            <a href="{% url 'home' %}"><img src="{% static '/svgs/logo.svg' %}" alt="Circlr" id="logo"></a>
          </div>
          <div class="nav-wrapper">
            <ul class="navigation">
              {% if user.is_authenticated %}
              <li><a href="{% url 'home' %}" {% url 'home' as home %}{% if request.path == home or request.path == '/accounts/' %} class="active"{% endif %}>Home</a></li>
              <li><a href="{% url 'matching' %}" {% if '/friends/' in request.path %}class="active"{% endif %}>Find Friends</a></li>
              <li><a href="{% url 'chat:index' %}" {% if '/chat/' in request.path %}class="active"{% endif %}>Messaging</a></li>
              <li><a href="{% url 'polls:index' %}" {% if '/polls/' in request.path %}class="active"{% endif %}>Polls</a></li>
              <li><a href="{% url 'forum-home' %}" {% if '/forums/' in request.path %}class="active"{% endif %}>Forums</a></li>
              <li class="drop">
                <input type="checkbox" id="drop" class="hidden" />
                <label for="drop" class="drop-btn"><span {% url 'accounts:profile' request.user.username as userpage %}{% if request.path == userpage %} class="active"{% endif %}>{{user.username}} </span><i class="arrow down"></i></label>
                <div class="dropdown">
                  <p><a href="{% url 'accounts:profile' request.user.username %}">Profile</a></p>
                  <p><a href="{% url 'accounts:logout' %}">Logout</a></p>
                </div>
              </li>
              {% else %}
              <li><a href="{% url 'forum-home' %}">Forums</a></li>
              <li><a href="{% url 'accounts:login'%}">Login</a></li>
              <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
              {% endif %}
            </ul>
          </div>
        </nav>
      </div>
		<div class="container">
			<br>
		</div>
	</div>
<div class="container">
<h3 class=" text-center">Messaging</h3>
<div class="messaging">
      <div class="inbox_msg">
        <div class="inbox_people">
          <div class="headind_srch">
            <div class="recent_heading">
              <h4>Recent</h4>
            </div>
            <!--
            <div class="srch_bar">
              <div class="stylish-input-group">
                <input type="text" class="search-bar"  placeholder="Search" >
                <span class="input-group-addon">
                <button type="button"> <i class="fa fa-search" aria-hidden="true"></i> </button>
                </span> </div>
            </div>-->
          </div>

        <div class="dummydiv" >
          <div class="inbox_chat">
            {%for item in recentlist%}
              <div class="chat_list" style="cursor:pointer;" onclick="roomNameGen('{{request.user.username}}','{{item.0}}')" >
                <div class="chat_people">
                  <div class="chat_img"> <img src="{{ item.0.userprofile.picture.url }}"  > </div>
                  <div class="chat_ib">
                    <h5>{{item.0.username}}<span class="chat_date">{{item.3}}</span></h5>
                    <p>{{item.1}} : {{item.2}}</p>
                  </div>
                </div>
              </div>
            {%endfor%}
              <div class="headind_srch" >
                <div class="recent_heading">
                  <h4>All Users</h4>
                </div>
              </div>
            {%for user in userlist%}
              {%if user.username != request.user.username %}
                <div class="chat_list" style="cursor:pointer;" onclick="roomNameGen('{{request.user.username}}','{{user.username}}')" >
                  <div class="chat_people">
                    <div class="chat_img"> <img src="{{ user.userprofile.picture.url }}"  > </div>
                    <div class="chat_ib">
                      <h5>{{user.username}}<span class="chat_date"></span></h5>
                      <p>Click to chat!</p>
                    </div>
                  </div>
                </div>
              {%endif%}
            {%endfor%}
          </div>
        </div>

        </div>
        <div class="mesgs">
          <div id="chat-log" class="msg_history">
            

          </div>
          <div class="type_msg">
            <div class="input_msg_write">
              <input id="chat-message-input" type="text" class="write_msg" placeholder="Type a message" />
              <button id="chat-message-submit" class="msg_send_btn" type="button"><i class="fa fa-paper-plane-o" aria-hidden="true"></i></button>
            </div>
          </div>
        </div>
      </div>




    </div></div>
    <script>

      function roomNameGen(userid,friendid){
        var roomName = [userid,friendid].sort().join("");
        document.cookie="userid="+userid;

        window.location.pathname = '/chat/' + roomName + '/';

      };


    </script>
</body>
</html>

chat/templates/chat/linkbroken.html
{% block content %}
    <h1>Sorry You don't have permissions to access this page or the link is broken</h1>
{% endblock content %}