api/urls.py
from django.urls import path,include,re_path
from api import views
from rest_framework.authtoken import views as authviews
urlpatterns = [
    path('userprofile',views.userprofile,name='userprofile'),
    path('testview',views.testview,name='testview'),
    path('interests',views.interests,name='interests'),
    path('friends',views.friends,name='friends'),
    path('friendrequest',views.friendrequest,name='friendrequest'),
    path('message',views.message,name='message'),
    path('forums',views.forums,name='forums'),
    path('topics',views.topics,name='topics'),
    path('posts',views.posts,name='posts'),
    path('polls',views.polls,name='polls'),
    path('vote',views.vote,name='vote'),
    re_path(r'^api-token-auth/', authviews.obtain_auth_token)
]

circlr/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from accounts import views as accounts_views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import PasswordResetCompleteView

urlpatterns = [
	path('reset/done/', PasswordResetCompleteView.as_view(template_name="accounts/reset_password_complete.html"), name="password_reset_complete"),
    path('admin/', admin.site.urls),
	path('api/',include('api.urls')),
    re_path(r'^accounts/', include('accounts.urls', namespace='accounts')),
    re_path(r'^$', accounts_views.home, name="home"),
    path('', include('django.contrib.auth.urls')),
    path('forums/', include('forums.urls')),
	path('friends/', include('friends.urls'), name="friends"),
    path('polls/', include('polls.urls')),
	re_path(r'^files/', include('files.urls')),
    re_path(r'^chat/', include('chat.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forums/urls.py
from django.urls import path
from . import views
from .views import *

urlpatterns = [
	path('', views.index, name='forum-home'),
	path('<slug>',views.forumpage,name='forumpage'),
	path('<forum>/<topic>',views.topicpage,name='topicpage'),
	path('new/', ForumCreateView.as_view(), name='forum-create'),
	path('(?P<slug>[-\w]+)/$/update', ForumUpdateView.as_view(), name='forum-update'),
	path('(?P<slug>[-\w]+)/$/delete', ForumDeleteView.as_view(), name='forum-delete'),
	path('<forum>/new/', TopicCreateView.as_view(), name='topic-create'),
	path('<forum>/(?P<slug>[\w-]+)/update', TopicUpdateView.as_view(), name='topic-update'),
	path('<forum>/(?P<slug>[\w-]+)/delete', TopicDeleteView.as_view(), name='topic-delete'),
	#path('<slug>/new/', views.topic_create_view, name='topic-create'),
	#path('<forum>/<slug>/delete', TopicDeleteView.as_view(), name='topic-delete'),
]
#(?P<slug>[-\w]+)/$

forums/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from django.template.defaultfilters import slugify

class Forum(models.Model):
	forumid = models.AutoField(primary_key=True, verbose_name='ID')
	forumname = models.CharField(max_length=30 , verbose_name= ('Name'))
	createdate = models.DateTimeField(default=timezone.now , verbose_name= ('Date Created'))
	creatorid = models.ForeignKey(User, on_delete=models.CASCADE , verbose_name= ('Creator'))
	viewprivacy = models.IntegerField(choices =((1, "Everyone"),
												(2, "People who are logged in."),
												(3, "Only You")),default=1, verbose_name= ('Who can view this forum'))
	writeprivacy = models.IntegerField(choices =((1,"People who are logged in"),
												(2,"Only You")),default=1, verbose_name= ('Who can create topics in this forum'))
	description = models.TextField(blank=True, null=True , verbose_name= ('Description'))
	slug = models.SlugField(('slug'), max_length=60, blank=True, unique=True)
	def __str__(self):
		return self.forumname
	def get_absolute_url(self):
		return reverse('forumpage', kwargs={'slug':self.slug})
	def save(self, *args, **kwargs):
		if not self.forumid:
			self.slug = slugify(self.forumname)+'-by-'+slugify(self.creatorid.username)+'-at-'+slugify(str(self.createdate)[-21:-13])+'-on-'+slugify(str(self.createdate)[:-22])
		if self.viewprivacy>self.writeprivacy+1:
			self.writeprivacy = self.viewprivacy-1
		super(Forum, self).save(*args, **kwargs)
	#forumimage
	#topics
	#subscribers

class Topic(models.Model):
	topicid = models.AutoField(primary_key=True, verbose_name= ('ID'))
	topicname = models.CharField(max_length=50, verbose_name= ('Name'))
	createdate = models.DateTimeField(default=timezone.now , verbose_name= ('Date Created'))
	creatorid = models.ForeignKey(User, on_delete=models.CASCADE , verbose_name= ('Creator'))
	viewprivacy = models.IntegerField(choices =((1, "Everyone"),
												(2, "People who are logged in."),
												(3, "Only You")),default=1, verbose_name= ('Who can view this topic'))
	writeprivacy = models.IntegerField(choices =((1,"Everyone"),
												(2, "People who are logged in."),
												(3,"Only You")),default=1, verbose_name= ('Who can post in this topic'))
	#viewcount = models.IntegerField(default=0)
	forumid = models.ForeignKey(Forum, on_delete=models.CASCADE)
	description = models.TextField(blank=True, null=True , verbose_name= ('Description'))
	slug = models.SlugField(('slug'), max_length=60, blank=True, unique=True)
	def __str__(self):
		return self.topicname
	def save(self, *args, **kwargs):
		if not self.topicid:
			self.slug = slugify(self.topicname)+'-by-'+slugify(self.creatorid.username)+'-at-'+slugify(str(self.createdate)[-21:-13])+'-on-'+slugify(str(self.createdate)[:-22])
		if int(self.forumid.viewprivacy) > int(self.viewprivacy):
			self.viewprivacy=str(self.forumid.viewprivacy)
		if int(self.viewprivacy) > int(self.writeprivacy):
			self.writeprivacy = self.viewprivacy
		super(Topic, self).save(*args, **kwargs)
	def get_absolute_url(self):
		return reverse('topicpage', kwargs={'forum':self.forumid.slug, 'topic':self.slug})

class Post(models.Model):
	postid = models.AutoField(primary_key=True, verbose_name= ('ID'))
	createdate = models.DateTimeField(default=timezone.now, verbose_name= ('Date Created'))
	creatorid = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name= ('Creator'), null=True, blank=True)
	topicid = models.ForeignKey(Topic, on_delete=models.CASCADE, verbose_name= ('Topic'))
	content = models.TextField(verbose_name= ('Content'))
	def __str__(self):
		return self.content

forums/forms.py
from django import forms
from django.utils import timezone

class CreateTopicForm(forms.Form):
	topicname = forms.CharField(label = "Name",max_length = 50)
	viewprivacy = forms.ChoiceField(choices =((1, "Public"),
												(2, "Group"),
												(3, "Private")),initial=1,label = "View Privacy")
	writeprivacy = forms.ChoiceField(choices =((1, "Public"),
												(2, "Group"),
												(3, "Private")),initial=1,label = "Write/Edit Privacy")
	description = forms.CharField(widget = forms.Textarea, label = "Description", required= False)

class CreatePostForm(forms.Form):
	content = forms.CharField(widget = forms.Textarea(attrs={'class':'posttext','style':'width:90%','rows':3}), label = "")

forums/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.http import HttpResponse
from .models import *
from .forms import CreateTopicForm, CreatePostForm
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from django.contrib.auth.models import User


def index(request):
	latest_forums = Forum.objects.order_by('-createdate')
	context = {'latest_forums':latest_forums}
	return render(request, 'forums/index.html', context)

def forumpage(request, slug):
	curr_forum = get_object_or_404(Forum, slug=slug)
	if curr_forum.viewprivacy == 1 or curr_forum.viewprivacy == 2 and request.user.is_authenticated or curr_forum.viewprivacy == 3 and request.user == curr_forum.creatorid:
		alltopics = curr_forum.topic_set.order_by('-createdate')
		context = {'topics':alltopics, 'forum':curr_forum}
		return render(request, 'forums/forum.html', context)
	else:
		return HttpResponse("<b>Nice try Loser!</b>")

def topicpage(request, forum, topic):
	curr_forum = get_object_or_404(Forum, slug=forum)
	curr_topic = get_object_or_404(Topic, slug=topic)
	if curr_forum.viewprivacy == 1 or curr_forum.viewprivacy == 2 and request.user.is_authenticated or curr_forum.viewprivacy == 3 and request.user == curr_forum.creatorid:
		if curr_topic.viewprivacy == 1 or curr_topic.viewprivacy == 2 and request.user.is_authenticated or curr_topic.viewprivacy == 3 and request.user == curr_topic.creatorid:
			allposts = curr_topic.post_set.all()
			postform = CreatePostForm()
			if request.method == 'POST':
				postform = CreatePostForm(request.POST)
				if postform.is_valid():
					finaldata = postform.cleaned_data
					if request.user.is_authenticated:
						finaldata['creatorid'] = request.user
					else:
						finaldata['creatorid'] = None
					finaldata['topicid'] = curr_topic
					Post.objects.create(**finaldata)
					return redirect('topicpage', forum, topic)
			context = {'posts':allposts, 'forum':curr_forum, 'topic':curr_topic, 'form':postform}
			return render(request, 'forums/topic.html', context)
		else:
			return HttpResponse("<b>Nice try Loser!</b>")
	else:
		return HttpResponse("<b>Nice try Loser!</b>")

class ForumCreateView(LoginRequiredMixin, CreateView):
	model = Forum
	fields = ['forumname', 'viewprivacy' , 'writeprivacy' , 'description']
	def form_valid(self, form):
		form.instance.creatorid = self.request.user
		return super().form_valid(form)

class ForumUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
	model = Forum
	fields = ['forumname', 'viewprivacy' , 'writeprivacy' , 'description']
	def form_valid(self, form):
		form.instance.creatorid = self.request.user
		return super().form_valid(form)
	def test_func(self):
		forum = self.get_object()
		if self.request.user == forum.creatorid:
			return True
		return False

class ForumDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
	model = Forum
	success_url = '/forums'
	def test_func(self):
		forum = self.get_object()
		if self.request.user == forum.creatorid:
			return True
		return False

class TopicCreateView(LoginRequiredMixin, CreateView):
	model = Topic
	fields = ['topicname', 'viewprivacy' , 'writeprivacy' , 'description']
	def dispatch(self, request, *args, **kwargs):
		if request.method.lower() in self.http_method_names:
				handler = getattr(self, request.method.lower(), self.http_method_not_allowed)
		else:
				handler = self.http_method_not_allowed
		self.request = request
		self.args = args
		self.kwargs = kwargs
		return handler(request, *args, **kwargs)
	def form_valid(self, form):
		form.instance.creatorid = self.request.user
		form.instance.forumid = Forum.objects.get(slug=self.kwargs['forum'])
		return super().form_valid(form)

class TopicUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
	model = Topic
	fields = ['topicname', 'viewprivacy' , 'writeprivacy' , 'description']
	def dispatch(self, request, *args, **kwargs):
		if request.method.lower() in self.http_method_names:
				handler = getattr(self, request.method.lower(), self.http_method_not_allowed)
		else:
				handler = self.http_method_not_allowed
		self.request = request
		self.args = args
		self.kwargs = kwargs
		return handler(request, *args, **kwargs)
	def form_valid(self, form):
		form.instance.creatorid = self.request.user
		form.instance.forumid = Forum.objects.get(slug=self.kwargs['forum'])
		return super().form_valid(form)
	def test_func(self):
		topic = self.get_object()
		if self.request.user == topic.creatorid:
			return True
		return False

class TopicDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
	model = Topic
	def get_success_url(self):
		topic = self.get_object()
		return reverse('forumpage', kwargs={'slug':topic.forumid.slug})
	def test_func(self):
		topic = self.get_object()
		if self.request.user == topic.creatorid:
			return True
		return False

forums/templates/forums/forum.html
{% extends "base.html" %}
{% block head %}
<title>
      Forums
</title>
{% endblock head %}
{% block css %}
{{ block.super }}
<style>
#Submit{
  color: #0083FD;
  background-color: rgb(200, 200, 200);
  transition: all 0.1s ease;
  cursor: pointer;
  width: 20%;
  border-color: #0083FD;
  border-radius: 100px;
  background: none;
  font-family: Sitefont-medium;
  font-size: 15px;
  padding: 7px;
}
#Submit:hover{
  color: rgb(200, 200, 200);
  background-color: #0083FD;
  transition: all 0.1s ease;
}
.row{
	margin-bottom: 20px;
}
.topiccont{
	padding: 20px 30px;
	background: rgba(0, 0, 0, 0.07);
	transition: background 2s ease;
	border-bottom: 0.5px solid black;
}
.topiccont a{
	text-decoration: none;
}
.topiccont a:hover{
	-webkit-filter: drop-shadow( -0.1px -0.1px 5px coral);
	filter: drop-shadow( -0.1px -0.1px 5px coral);
}
.topiccont span{
	color: #0083FD;
}
.topiccont:nth-of-type(1){
	border-top: 0.5px solid black;
}
.topiccont:hover{
	background: rgba(0, 0, 0, 0.25);
	transition: background 1s ease;
	cursor: pointer;
}
.topicname {
	font-size: 25px;
	margin-bottom: 0px;
}
@media screen and (max-width: 750px) {
	#Submit{
		width: 30%;
	}
}
@media screen and (max-width: 550px) {
	#Submit{
		width: 38%;
		border-radius: 2em;
	}
	h1{
		font-size: 25px;
	}
}
.navhelp {
	font-size: 15px;
}
.topicarea{
	margin-top: 50px;
}
#forumdesc::-webkit-scrollbar{
    width: 0px;
    background: transparent; /* make scrollbar transparent */
}
#forumdesc{
	margin-top: -15px;
	width:50%;
	float:left;
	height:100px;
	overflow: scroll;
	overflow-x: hidden;
}
</style>
{% endblock css %}
{% block content %}
<div class="sidepad" style="width:10%;margin-top:80px;padding:10px;float: left;"></div>
<div class="sidepad" style="width:10%;margin-top:80px;padding:10px;float: right;"></div>
<div class="centercontent" style="width:80%;max-width:1400px;margin-top:20px;padding:10px;float: right;">
	<p class="navhelp"><a style="text-decoration:none " href="{% url 'forum-home' %}">Forums</a>/<a style="text-decoration:none " href="{% url 'forumpage' forum.slug %}">{{ forum.forumname }}</a></p>
	<div class="row">
		{% if user == forum.creatorid %}
			<button id="Submit" onclick="window.location.href='{% url "forum-delete" forum.slug %}'" style="float: right; margin-left:10px;">Delete Forum</button>
			<button id="Submit" onclick="window.location.href='{% url "forum-update" forum.slug %}'" style="float: right;">Edit Forum</button>
		{% endif %}
		<h1>Forum : {{forum.forumname}}</h1><br><div style="margin-top:-35px;margin-bottom: 12px;font-size: 20px;">Description :</div><br>
		<div id="forumdesc">
			<p>{% if forum.description %}{{forum.description}}{% else %}<span style="color:rgba(0, 255, 255, 0.5);">No Description</span>{% endif %}</p>
		</div>
		{% if forum.writeprivacy == 2 and user == forum.creatorid or forum.writeprivacy == 1 and user.is_authenticated %}
			<button id="Submit" onclick="window.location.href='{% url "topic-create" forum.slug %}'" style="float: right;margin-top: -20px;">Create a Topic</button><br>
		{% endif %}
	</div>
	<br>
	<div class="topicarea">
		Topics:<br>
		{% if topics %}
			{% for topic in topics %}
				{% if topic.viewprivacy == 3 and user == topic.creatorid or topic.viewprivacy == 2 and user.is_authenticated or topic.viewprivacy == 1%}
				<a href="{% url 'topicpage' topic.forumid.slug topic.slug %}">
					<div class="topiccont" onclick="window.location.href='{% url "topicpage" topic.forumid.slug topic.slug %}'">
						<div class="topicname">
							<span style="float: left;">{{ topic.topicname }}</span>
						</div><br><br>
						<div class="forumdet">
							<span style="float: right">Published on {{ topic.createdate.date }} at <span class="hr">{{ topic.createdate.time.hour }}:</span><span class="min">{{ topic.createdate.time.minute }}</span><span class="am/pm"> </span></span>
							<span id="creator" style="float: left;">Created by :&nbsp;<a href="../accounts/profile/{{topic.creatorid.username}}">{{ topic.creatorid.username }}</a></span>
						</div>
					</div>
				</a>
				{% endif %}
			{% endfor %}
		{% else %}
			<p>No topics are available. {% if forum.writeprivacy == 1 %}{% if user.is_authenticated %}Go create some!{% else %}Log-in to create some!{% endif %}{% endif %} </p>
		{% endif %}
	</div>
</div>
<script>
	window.onload(updatetime());
</script>
{% endblock %}

forums/templates/forums/forum_confirm_delete.html
{% extends "base.html" %}
{% block head %}
<title>
      Confirm Delete
</title>
{% endblock head %}
{% block css %}
{{ block.super }}
<style>
	#Submit{
  color: #0083FD;
  background-color: rgb(200, 200, 200);
  transition: all 0.1s ease;
  cursor: pointer;
  width: 49%;
  border-color: #0083FD;
  border-radius: 100px;
  background: none;
  font-family: Sitefont-medium;
  font-size: 15px;
  padding: 7px;
}
#Submit:hover{
  color: rgb(200, 200, 200);
  background-color: #0083FD;
  transition: all 0.1s ease;
}
</style>
{% endblock css %}
{% block content %}
<div class="sidepad" style="width:33%;margin-top:80px;padding:10px;float: left;"></div>
<div class="sidepad" style="width:33%;margin-top:80px;padding:10px;float: right;"></div>
<div class="centercontent" style="width:34%;max-width:1400px;margin-top:20px;padding:10px;float: right;">
	<form method="POST">
		{% csrf_token %}
		<h1>Delete Forum</h1>
		<h2>Are You Sure You Want To Delete the Forum "{{ forum.forumname }}"</h2><br>
		<button id="Submit" type="submit">Yes, Delete</button>
		<button id="Submit" onclick="window.location.href='{% url "forumpage" forum.slug %}'; event.preventDefault();">Cancel</a>
	</form>
</div>
{% endblock content %}

forums/templates/forums/topic.html
{% extends "base.html" %}
{% load static %}
{% block css %}
{{ block.super }}
<style>
@font-face {
	font-family: 'Material Icons';
	font-style: normal;
	font-weight: 400;
	src: url({% static 'fonts/Material_Icons' %}.woff2) format('woff2');
}
#Submit{
  color: #0083FD;
  background-color: rgb(200, 200, 200);
  transition: all 0.1s ease;
  cursor: pointer;
  width: 20%;
  border-color: #0083FD;
  border-radius: 100px;
  background: none;
  font-family: Sitefont-medium;
  font-size: 15px;
  padding: 7px;
}
#Submit:hover{
  color: rgb(200, 200, 200);
  background-color: #0083FD;
  transition: all 0.1s ease;
}
#Submit-post{
  width: 10%;
  border-radius: 2px 2px 10px 2px;
  height:100px;
  color: #0083FD;
  background-color: rgb(200, 200, 200);
  transition: all 0.1s ease;
  cursor: pointer;
  border-color: #0083FD;
  background: none;
  font-family: Sitefont-medium;
  font-size: 15px;
  padding: 7px;
  margin-top: 20px;
}
#Submit-post:hover{
  color: rgb(200, 200, 200);
  background-color: #0083FD;
  transition: all 0.1s ease;
}
#Submit-attachment{
  width: 5%;
  border-radius: 2px;
  height:100px;
  color: #0083FD;
  background-color: rgb(200, 200, 200);
  transition: all 0.1s ease;
  cursor: pointer;
  border-color: #0083FD;
  background: none;
  font-family: Sitefont-medium;
  font-size: 15px;
  padding: 7px;
  margin-top: 20px;
}
#Submit-attachment:hover{
  color: rgb(200, 200, 200);
  background-color: #0083FD;
  transition: all 0.1s ease;
}
#Submit-attachment i{
	transform: scale(1.5) rotate(-90deg);
}
#id_content{
	width: 85%!important;
	height: 100px;
	resize: none;
	border-radius: 2px 2px 2px 10px;
	outline: none;
	margin-top: 20px;
}
.row{
	margin-bottom: 20px;
}
.postcont{
	padding: 20px 30px;
	background: rgba(0, 0, 0, 0.07);
	transition: background 2s ease;
	border-bottom: 0.5px solid black;
	overflow: auto;
}
.postcont a{
	text-decoration: none;
}
.postcont a:hover{
	-webkit-filter: drop-shadow( -0.1px -0.1px 5px coral);
	filter: drop-shadow( -0.1px -0.1px 5px coral);
}
.postcont span{
	color: #0083FD;
}
.postcont:nth-of-type(1){
	border-top: 0.5px solid black;
}
.postcont:hover{
	background: rgba(0, 0, 0, 0.25);
	transition: background 1s ease;
}
@media screen and (max-width: 750px) {
	#Submit{
		width: 30%;
	}
}
@media screen and (max-width: 550px) {
	#Submit{
		width: 38%;
		border-radius: 2em;
	}
	h1{
		font-size: 25px;
	}
}
.navhelp {
	font-size: 15px;
}
.postarea{
	margin-top: 50px;
}
#topicdesc::-webkit-scrollbar{
    width: 0px;
    background: transparent; /* make scrollbar transparent */
}
#topicdesc{
	margin-top: -15px;
	width:50%;
	float:left;
	height:110px;
	overflow: scroll;
	overflow-x: hidden;
}
.material-icons {
  font-family: 'Material Icons';
  font-weight: normal;
  font-style: normal;
  font-size: 24px;
  line-height: 1;
  letter-spacing: normal;
  text-transform: none;
  display: inline-block;
  white-space: nowrap;
  word-wrap: normal;
  direction: ltr;
  -webkit-font-feature-settings: 'liga';
  -webkit-font-smoothing: antialiased;
}
.content{
	margin-left:-50px;
	overflow:unset;
	overflow-x: hidden;
}
.content a{
	text-decoration: none;
}
.modal {
    z-index: 9999;
    display: none;
    padding-top: 300px;
    position: fixed;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    overflow: auto;
    background-color: rgb(0, 0, 0);
    background-color: rgba(0, 0, 0, 0.4)
}
.card{
    box-shadow: 0 4px 10px 0 rgba(0, 0, 0, 0.07), 0 4px 20px 0 rgba(0, 0, 0, 0.19)
}
.animate-top {
    position: relative;
    animation: animatetop 0.4s
}
@keyframes animatetop {
    from {
        top: -300px;
        opacity: 0
    }
    to {
        top: 0px;
        opacity: 1
    }
}
.modal-content {
    margin: auto;
    background-color: #fff;
    position: relative;
    padding: 0;
    outline: 0;
	width: 300px;
	z-index: 9999;
	height: auto;
	max-height: 800px;
	overflow-y:initial;
	overflow-x: hidden;
}
.top-right {
    position: absolute;
    right: 0;
	top: 0;
	float:right;
}
.close{
	color: #0083FD;
	background-color: #343233;
	transition: color 0.5s ease;
	transition: background-color 0.5s ease; 
	border: none;
	height: 30px;
	width: 30px;
}
.close:hover{
	color: #343233;
	background-color: #0083FD;
	transition: color 0.5s ease;
	transition: background-color 0.5s ease; 
}
</style>
{% endblock css %}
{% block content %}
<div class="sidepad" style="width:10%;margin-top:80px;padding:10px;float: left;"></div>
<div class="sidepad" style="width:10%;margin-top:80px;padding:10px;float: right;"></div>
<div class="centercontent" style="width:80%;max-width:1400px;margin-top:20px;padding:10px;float: right;">
	<p class="navhelp"><a style="text-decoration:none " href="{% url 'forum-home' %}">Forums</a>/<a style="text-decoration:none " href="{% url 'forumpage' topic.forumid.slug %}">{{ topic.forumid.forumname }}</a>/<a style="text-decoration:none " href="{% url 'topicpage' topic.forumid.slug topic.slug %}">{{ topic.topicname }}</a></p>
	<div class="row">
		{% if user == topic.creatorid %}
			<button id="Submit" onclick="window.location.href='{% url "topic-delete" forum.slug topic.slug %}'" style="float: right; margin-left:10px;">Delete Topic</button>
			<button id="Submit" onclick="window.location.href='{% url "topic-update" forum.slug topic.slug %}'" style="float: right;">Edit Topic</button>
		{% endif %}
		<h1>Topic : {{topic.topicname}}</h1><br><div style="margin-top:-35px;margin-bottom: 12px;font-size: 20px;">Description :</div><br>
		<div id="topicdesc">
			<p>{% if topic.description %}{{topic.description}}{% else %}<span style="color:rgba(0, 255, 255, 0.5);">No Description</span>{% endif %}</p>
		</div>
	</div><br><br>
	<div class="postarea">
		<div style="margin-bottom: 17px;font-size: 20px;">Posts:</div>
		{% if posts %}
		{% for post in posts %}
			<div class="postcont">
				<div class="content">
					<span style="float: left;">{{ post.content }}</span>
				</div><br><br>
				<div class="postdet">
					<span style="float: right;margin-bottom:5px;">Published on {{ post.createdate.date }} at <span class="hr">{{ post.createdate.time.hour }}:</span><span class="min">{{ post.createdate.time.minute }}</span><span class="am/pm"> </span></span>
					<span id="creator" style="float: left;margin-bottom:5px;">Written by :&nbsp;{% if post.creatorid %}<a href="../../accounts/profile/{{post.creatorid.username}}">{{ post.creatorid.username }}</a>{% else %}Anonymous User{% endif %}</span>
				</div>
			</div>
		{% endfor %}
		{% else %}
			<p>No posts are available. Go create some!</p>
		{% endif %}
		<form method="POST">{% csrf_token %}
			<div class="row">
				{{ form }}
				<input id="Submit-post" type="submit" value="Post" style="float:right">
				<button id="Submit-attachment" style="float: right" onclick="document.getElementById('modal').style.display='block'"><i class="material-icons">attachment</i></button>
			</div>
		</form>
		<div id="modal" class="modal">
			<div class="modal-content animate-top card">
				<header style="background:#343233;height: 30px;"> 
					<button onclick="closemodal()" class="close top-right">&times;</button>
					<h2 style="margin-top: 0px;color: #0083FD;">Upload Files</h2>
				</header>
				<iframe id="files_frame" name="files_frame" src="{% url 'fileindex' %}"></iframe>
			</div>
		</div>
	</div>
</div>
<script>
	window.onload(updatetime);
	function closemodal(){
		document.getElementById('files_frame').src="{% url 'fileindex' %}"
		document.getElementById('modal').style.display='none';
	}
</script>
{% endblock %}