api/urls.py
from django.urls import path,include,re_path
from api import views
from rest_framework.authtoken import views as authviews
urlpatterns = [
    path('userprofile',views.userprofile,name='userprofile'),
    path('testview',views.testview,name='testview'),
    path('interests',views.interests,name='interests'),
    path('friends',views.friends,name='friends'),
    path('friendrequest',views.friendrequest,name='friendrequest'),
    path('message',views.message,name='message'),
    path('forums',views.forums,name='forums'),
    path('topics',views.topics,name='topics'),
    path('posts',views.posts,name='posts'),
    path('polls',views.polls,name='polls'),
    path('vote',views.vote,name='vote'),
    re_path(r'^api-token-auth/', authviews.obtain_auth_token)
]

circlr/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from accounts import views as accounts_views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import PasswordResetCompleteView

urlpatterns = [
	path('reset/done/', PasswordResetCompleteView.as_view(template_name="accounts/reset_password_complete.html"), name="password_reset_complete"),
    path('admin/', admin.site.urls),
	path('api/',include('api.urls')),
    re_path(r'^accounts/', include('accounts.urls', namespace='accounts')),
    re_path(r'^$', accounts_views.home, name="home"),
    path('', include('django.contrib.auth.urls')),
    path('forums/', include('forums.urls')),
	path('friends/', include('friends.urls'), name="friends"),
    path('polls/', include('polls.urls')),
	re_path(r'^files/', include('files.urls')),
    re_path(r'^chat/', include('chat.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.urls import path

from . import views
app_name = "polls"
urlpatterns = [
    path('',views.index,name="index"),
    path('<int:question_id>/', views.detail, name="detail"),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name="vote"),
    path('questions/', views.questions , name='questions'),
    path('choices/', views.choices, name='choices'),
    path('savechoices/', views.savechoices, name='savechoices'),

]

polls/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    #pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question,on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text
class Voter(models.Model):
    question_id = models.CharField(max_length=200)
    user = models.CharField(max_length=200)


# Create your models here.

polls/views.py
from django.shortcuts import render,get_object_or_404
from .models import Question,Choice,Voter
from django.http import HttpResponse,HttpResponseRedirect,Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required

@login_required
def index(request):
    latest_question_list = Question.objects.all()
    context = {'latest_question_list': latest_question_list}
    return render(request,'polls/index.html',context)
# Create your views here.
@login_required
def detail(request,question_id):
    if Voter.objects.filter(question_id=question_id,user=request.user.username).exists():
        return render(request,'polls/alreadyvoted.html')
    else:
        question = get_object_or_404(Question,pk=question_id)
        return render(request,'polls/detail.html',{'question':question})
@login_required
def results(request,question_id):
    question = get_object_or_404(Question,pk=question_id)
    return render(request,'polls/results.html',{'question':question})
@login_required
def vote(request,question_id):
    question = get_object_or_404(Question,pk=question_id)
    if Voter.objects.filter(question_id=question_id,user=request.user.username).exists():
        #return HttpResponse("YOU ALREADY VOTED")
        return render(request,'polls/alreadyvoted.html',{'question.id':question_id})
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError,Choice.DoesNotExist):
        return render(request,'polls/detail.html',{
            'question':question,
            'error_message':"You Didnt select a choice",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        Voter.objects.create(question_id=question_id,user=request.user.username)
        return HttpResponseRedirect(reverse('polls:results',args=[question.id]))
@login_required
def questions(request):
    return render(request,'polls/questions.html')
def choices(request):
    question = request.POST['question']
    number = request.POST['number']
    questionlogid = Question.objects.create(question_text=question)
    context = {'question': questionlogid.pk , 'number':list(range(int(number)))}
    return render(request,'polls/choices.html',context)
@login_required
def savechoices(request):
    number = request.POST['number']
    question = request.POST['question']
    questions = Question.objects.get(pk=question)
    number = [int(i) for i in number[1:-1].split(",")]
    if len(Choice.objects.filter(question=questions))==0:
        for x in number:
            s = request.POST['choice'+str(x+1)]
            choicelogid = Choice.objects.create(question = questions,choice_text=s)
    return render(request,'polls/added.html',{"questionid":questions.pk})

polls/templates/polls/added.html
{% extends 'base.html' %}
{% block css %}
{{block.super}}
<style>
    #Submit {
        color: #0083FD;
        background-color: rgb(200, 200, 200);
        transition: all 0.1s ease;
        cursor: pointer;
        width: 50%;
        border-color: #0083FD;
        border-radius: 100px;
        background: none;
        font-family: Sitefont-medium;
        font-size: 15px;
        padding: 7px;
        margin-top: 30px;
    }

    #Submit:hover {
        color: rgb(200, 200, 200);
        background-color: #0083FD;
        transition: all 0.1s ease;
    }
    h1{
        font-size: 50px;
    }
</style>
{% endblock css %}
{% block content %}
{% load static %}
<div class="sidepad" style="width:33%;margin-top:80px;padding:10px;float: left;"></div>
<div class="sidepad" style="width:33%;margin-top:80px;padding:10px;float: right;"></div>
<div class="centercontent" style="margin-top:80px;width:34%;padding:10px;float: right;">
    <center>
        <h1>Your poll was added succesfully!!</h1>
        <input style="opacity: 0; pointer-events: none;" value="127.0.0.1:8000/polls/{{ questionid }}" id="share"><br>
        <button id="Submit" onclick="myFunction()" name="action">Share Poll</button>
        <button id="Submit" onclick='window.location.href="{% url 'polls:index' %}"' name="action">Answer some polls</button>
    </center>
</div>
<script>
    function myFunction() {
        /* Get the text field */
        var copyText = document.getElementById("share");

        /* Select the text field */
        copyText.select();

        /* Copy the text inside the text field */
        document.execCommand("copy");

        /* Alert the copied text */
        alert("Copied to clipboard: " + copyText.value);
    }
</script>
{% endblock content %}

polls/templates/polls/alreadyvoted.html
{% extends 'base.html' %}
{% block css %}
{{block.super}}
<style>
    #Submit {
        color: #0083FD;
        background-color: rgb(200, 200, 200);
        transition: all 0.1s ease;
        cursor: pointer;
        width: 50%;
        border-color: #0083FD;
        border-radius: 100px;
        background: none;
        font-family: Sitefont-medium;
        font-size: 15px;
        padding: 7px;
        margin-top: 10px;
    }

    #Submit:hover {
        color: rgb(200, 200, 200);
        background-color: #0083FD;
        transition: all 0.1s ease;
    }
</style>
{% endblock css %}
{% block content %}
<div class="sidepad" style="width:33%;margin-top:80px;padding:10px;float: left;"></div>
<div class="sidepad" style="width:33%;margin-top:80px;padding:10px;float: right;"></div>
<div class="centercontent" style="width:34%;padding:10px;float: right;">
    <center>
        <h1>You have already voted for this poll.</h1><br>
        <button id="Submit" onclick='window.location.href="{{ request.path}}results"'>View Results</a>
    </center>
</div>
{% endblock content %}

polls/templates/polls/choices.html
{% extends 'base.html' %}
{% block css %}
{{block.super}}
<style>
    #Submit {
        color: #0083FD;
        background-color: rgb(200, 200, 200);
        transition: all 0.1s ease;
        cursor: pointer;
        width: 50%;
        border-color: #0083FD;
        border-radius: 100px;
        background: none;
        font-family: Sitefont-medium;
        font-size: 15px;
        padding: 7px;
        margin-top: 30px;
    }

    #Submit:hover {
        color: rgb(200, 200, 200);
        background-color: #0083FD;
        transition: all 0.1s ease;
    }
</style>
{% endblock css %}
{% block content %}
<div class="sidepad" style="width:33%;margin-top:80px;padding:10px;float: left;"></div>
<div class="sidepad" style="width:33%;margin-top:80px;padding:10px;float: right;"></div>
<div class="centercontent" style="margin-top:80px;width:34%;padding:10px;float: right;">
  <h2>Enter Your Options Here</h2>
  <form action="{% url 'polls:savechoices' %}" method="POST"><br>
    {% csrf_token %}
    {% for choice in number %}
    <label for="c{{ forloop.counter }}">Choice number {{forloop.counter}}</label>
    <input name="choice{{ forloop.counter }}" type="text" id="c{{ forloop.counter }}" class="validate">
    {% endfor %}
    <input name="number" id="i1" class="hidden" value="{{ number }}" hidden>
    <input name="question" id="i2" class="hidden" value="{{ question }}" hidden>
    <center>
      <button id="Submit" type="submit" name="action">Next</button>
    </center>
  </form>
</div>
{% endblock content %}

polls/templates/polls/detail.html
{% extends 'base.html' %}
{% block css %}
{{block.super}}
<style>
    *{
        transition: font-size 0.5s ease;
    }
    #Submit {
        color: #0083FD;
            background-color: rgb(200, 200, 200);
            transition: all 0.1s ease;
            cursor: pointer;
            width: 50%;
            border-color: #0083FD;
            border-radius: 100px;
            background: none;
            font-family: Sitefont-medium;
            font-size: 15px;
            padding: 7px;
            margin-top: 10px;
        }
    
        #Submit:hover {
            color: rgb(200, 200, 200);
            background-color: #0083FD;
            transition: all 0.1s ease;
        }
    
        h1 {
            font-size: 3em;
            margin-bottom: 80px;
        }
        .leftpart {
            box-shadow: 20px 20px 20px -15px #000000;
            position: fixed;
            height: auto;
        }
        .polllist li{
            margin: 50px 50px;
            margin-left: -30px;
            list-style-type: none;
            transition: background 1s ease;
        }
        .polllist a li{
            font-size: 25px;
        }
        .polllist a{
            text-decoration: none;
        }
        .polllist li:hover{
            background: rgba(0, 0, 0, 0.07);
            transition: background 1s ease;
        }
        h2{
            font-size: 3em;
        }
        @media screen and (max-width: 980px) {
            h2{
                font-size: 2.7em;
                transition: font-size 0.5s ease;
            }
        }
        @media screen and (max-width: 880px) {
            h1{
                font-size: 3.5em;
                transition: font-size 0.5s ease;
            }
            #Submit{
                width: 70%;
            }
        }
        @media screen and (max-width: 650px) {
            h1{
                font-size: 2.3em;
                transition: font-size 0.5s ease;
            }
            h2{
                font-size: 1.8em;
            }
            #Submit{
                width: 100%;
            }
            .radio-label{
                font-size: 1em;
            }
        }
    .question{
        overflow:scroll;
        height: 320px;
        overflow-x: hidden;
    }
    .question::-webkit-scrollbar{
        width: 0px;
        background: transparent; /* make scrollbar transparent */
    }
    </style>
{% endblock css %}
{% block content %}
<div class="leftpart" style="width:50%;height: 80vh;vertical-align: middle;">
    <div class="sidepad" style="width:10%;margin-top:80px;padding:10px;float: left;"></div>
    <div class="sidepad" style="width:10%;margin-top:80px;padding:10px;float: right;"></div>
    <div class="centercontent" style="width:80%;max-width:1400px;margin-top:80px;padding:10px;float: right;">
        <center>
            <h1>Poll Question :<br><div class="question">{{ question.question_text }}</h1>
        </center>
    </div>
</div>
<div style="width:50%;float:right;height: 80vh; vertical-align: middle;">
    <div class="sidepad" style="width:10%;margin-top:80px;padding:10px;float: left;"></div>
    <div class="sidepad" style="width:10%;margin-top:80px;padding:10px;float: right;"></div>
    <div class="centercontent" style="width:80%;max-width:1400px;margin-top:30px;padding:10px;float: right;">
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        <h2>Options :</h2>
        <form action="{% url 'polls:vote' question.id %}" method="post">
            {% csrf_token %}
            {% for choice in question.choice_set.all %}
            <div class="radio">
                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                <label for="choice{{ forloop.counter }}" class="radio-label">{{ choice.choice_text }}</label><br>
            </div>
            {% endfor %}
            <input type="submit" id="Submit" value="Vote">
        </form>
    </div>
</div>
{% endblock content %}

polls/templates/polls/index.html
{% extends 'base.html' %}
{% block css %}
{{block.super}}
<style>
    *{
        transition: font-size 0.5s ease;
    }
    #Submit {
        color: #0083FD;
        background-color: rgb(200, 200, 200);
        transition: all 0.1s ease;
        cursor: pointer;
        width: 50%;
        border-color: #0083FD;
        border-radius: 100px;
        background: none;
        font-family: Sitefont-medium;
        font-size: 15px;
        padding: 7px;
        margin-top: 10px;
    }

    #Submit:hover {
        color: rgb(200, 200, 200);
        background-color: #0083FD;
        transition: all 0.1s ease;
    }

    h1 {
        font-size: 3em;
        margin-bottom: 80px;
    }
    .leftpart {
        box-shadow: 20px 20px 20px -15px #000000;
        position: fixed;
        height: auto;
    }
    .polllist li{
        margin: 50px 50px;
        margin-left: -30px;
        list-style-type: none;
        transition: background 1s ease;
    }
    .polllist a li{
        font-size: 25px;
    }
    .polllist a{
        text-decoration: none;
    }
    .polllist li:hover{
        background: rgba(0, 0, 0, 0.07);
        transition: background 1s ease;
    }
    h2{
        font-size: 3em;
    }
    @media screen and (max-width: 980px) {
        h2{
            font-size: 2.7em;
            transition: font-size 0.5s ease;
        }
    }
    @media screen and (max-width: 880px) {
        h1{
            font-size: 3.5em;
            transition: font-size 0.5s ease;
        }
        #Submit{
            width: 70%;
        }
    }
    @media screen and (max-width: 650px) {
        h1{
            font-size: 2.5em;
            transition: font-size 0.5s ease;
        }
        h2{
            font-size: 2em;
        }
        #Submit{
            width: 100%;
        }
    }
    @media screen and (max-width: 500px) {
        h1{
            font-size: 2em;
            transition: font-size 0.5s ease;
        }
        h2{
            font-size: 1.7em;
        }
    }
</style>
{% endblock css %}
{% block content %}
<div class="leftpart" style="width:50%;height: 80vh;vertical-align: middle;">
    <div class="sidepad" style="width:10%;margin-top:80px;padding:10px;float: left;"></div>
    <div class="sidepad" style="width:10%;margin-top:80px;padding:10px;float: right;"></div>
    <div class="centercontent" style="width:80%;max-width:1400px;margin-top:80px;padding:10px;float: right;">
        <center>
            <h1>Welcome to the polls page</h1>
            <button id="Submit" onclick="window.location.href='{% url 'polls:questions' %}';">Create Your Own Poll Now</a>
        </center>
    </div>
</div>
<div style="width:50%;float:right;height: 80vh; vertical-align: middle;">
    <div class="sidepad" style="width:10%;margin-top:80px;padding:10px;float: left;"></div>
    <div class="sidepad" style="width:10%;margin-top:80px;padding:10px;float: right;"></div>
    <div class="centercontent" style="width:80%;max-width:1400px;margin-top:30px;padding:10px;float: right;">
        <h2>Available polls :</h2>
        {% if latest_question_list %}
        <ul class="polllist">
            {% for question in latest_question_list %}
            <a href="{% url 'polls:detail' question.id %}"><li width="100%">{{ question.question_text }}</li></a>
            {% endfor %}
        </ul>
        {% else %}
        <h2 style="font-size:15px;">No polls are available right now. Go create some!</h2>
        {% endif %}
    </div>
</div>
{% endblock content %}

polls/templates/polls/questions.html
{% extends 'base.html' %}
{% block css %}
{{block.super}}
<style>
    #Submit {
        color: #0083FD;
        background-color: rgb(200, 200, 200);
        transition: all 0.1s ease;
        cursor: pointer;
        width: 50%;
        border-color: #0083FD;
        border-radius: 100px;
        background: none;
        font-family: Sitefont-medium;
        font-size: 15px;
        padding: 7px;
        margin-top: 30px;
    }

    #Submit:hover {
        color: rgb(200, 200, 200);
        background-color: #0083FD;
        transition: all 0.1s ease;
    }
</style>
{% endblock css %}
{% block content %}
<div class="sidepad" style="width:33%;margin-top:80px;padding:10px;float: left;"></div>
<div class="sidepad" style="width:33%;margin-top:80px;padding:10px;float: right;"></div>
<div class="centercontent" style="margin-top:80px;width:34%;padding:10px;float: right;">
<h2>Register a Question</h2>
  <form id="ajax_form1" action="{% url 'polls:choices' %}" method="POST"><br>
    {% csrf_token %}
    <label for="question" style="font-size:20px">Question</label>
    <input name="question" type="text" id="question" placeholder="Enter your question for the poll." class="validate" required>
    <br>
    <label for="number" style="font-size:20px">No. of Choices</label>
    <input name="number" type="number" id="number" placeholder="Enter number of choices." class="validate" required>
    <center><button id="Submit" type="submit" name="action">Next</center>
  </form>
</div>
<script type="text/javascript">
  $(document).on('submit', '#ajax_form', function (ajax_form1) {
    ajax_form1.preventDefault();
    $.ajax({
      type: 'POST',
      url: 'polls:choices/',
      data: {
        question: $('#question').val(),
        number: $('#number').val(),
        csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
      },
    })
  });
  console.log(question.value)

</script>
{% endblock content %}

polls/templates/polls/results.html
{% extends 'base.html' %}
{% block content %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>
{% block css %}
{{block.super}}
<style>
    * {
        transition: font-size 0.5s ease;
    }

    #Submit {
        color: #0083FD;
        background-color: rgb(200, 200, 200);
        transition: all 0.1s ease;
        cursor: pointer;
        width: 50%;
        border-color: #0083FD;
        border-radius: 100px;
        background: none;
        font-family: Sitefont-medium;
        font-size: 15px;
        padding: 7px;
        margin-top: 10px;
    }

    #Submit:hover {
        color: rgb(200, 200, 200);
        background-color: #0083FD;
        transition: all 0.1s ease;
    }

    h1 {
        font-size: 3em;
        margin-bottom: 80px;
    }

    .leftpart {
        box-shadow: 20px 20px 20px -15px #000000;
        position: fixed;
        height: auto;
    }

    .polllist li {
        margin: 50px 50px;
        margin-left: -45px;
        list-style-type: none;
        transition: background 1s ease;
        font-size: 25px;
        transition: font-size 0.5s ease;
    }
    .testtext{
        font-size: 25px;
        transition: font-size 0.5s ease;
    }

    .polllist li:hover {
        background: rgba(0, 0, 0, 0.07);
        transition: background 1s ease;
    }

    @media screen and (max-width: 880px) {
        h1 {
            font-size: 3.5em;
            transition: font-size 0.5s ease;
        }

        #Submit {
            width: 70%;
        }
        .polllist li, .testtext{
            font-size: 20px;
            transition: font-size 0.5s ease;
        }
    }

    @media screen and (max-width: 650px) {
        h1 {
            font-size: 2.3em;
            transition: font-size 0.5s ease;
        }

        #Submit {
            width: 100%;
        }
        .polllist li, .testtext{
            font-size: 15px;
            transition: font-size 0.5s ease;
        }
    }
    @media screen and (max-width: 500px) {
        .polllist li, .testtext{
            font-size: 14px;
            transition: font-size 0.5s ease;
            margin-left: -20px;
        }

        .testtext{
            margin-left: 10px;
        }
        .rightpart .sidepad{
            width: 0;
        }
        .rightpart .centercontent{
            width: 100%!important;
        }
    }
    .chartcontainer{
        height: 60%;
        width: 60%;
        margin-top:-70px;
    }
    .question{
        overflow:scroll;
        height: 100px;
        overflow-x: hidden;
    }
    .question::-webkit-scrollbar{
        width: 0px;
        background: transparent; /* make scrollbar transparent */
    }
</style>
{% endblock css %}
<div class="leftpart" style="width:50%;height: 80vh;vertical-align: middle;">
    <div class="sidepad" style="width:10%;margin-top:80px;padding:10px;float: left;"></div>
    <div class="sidepad" style="width:10%;margin-top:80px;padding:10px;float: right;"></div>
    <div class="centercontent" style="width:80%;max-width:1400px;margin-top:80px;padding:10px;float: right;">
        <center>
            <h1 style="margin-top:-60px;">Results for :<br><div class="question">{{ question.question_text }}</div></h1>
            <div class="chartcontainer"><canvas id="pie-chart" width="100%" height="100%"></canvas></div>
        </center>
    </div>
</div>
<div class="rightpart" style="width:50%;float:right;height: 80vh; vertical-align: middle;">
    <div class="sidepad" style="width:10%;margin-top:80px;padding:10px;float: left;"></div>
    <div class="sidepad" style="width:10%;margin-top:80px;padding:10px;float: right;"></div>
    <div class="centercontent" style="width:80%;max-width:1400px;margin-top:50px;padding:10px;float: right;">
        <span class="testtext" style="float:left;margin-right: 5px;">Choice</span><span class="testtext" style="float:right;margin-right: 50px;">Votes</span><br>
        <ul class="polllist">
            {% for choice in question.choice_set.all %}
            <li><span style="float:left;margin-right: 5px;">{{ choice.choice_text }}</span><span style="float:right">{{ choice.votes }} vote{{ choice.votes|pluralize }}</span><br></li>
            {% endfor %}
        </ul>
        <center><button id="Submit" onclick="window.location.href='{% url "polls:index" %}'">Vote Again ?</button></center>
    </div>
</div>
<script>

    var c_text = [];
    var c_votes = [];
    {% for choice in question.choice_set.all %}
        c_text.push("{{ choice.choice_text }}")
        c_votes.push("{{ choice.votes }}")
    {% endfor %}


    new Chart(document.getElementById("pie-chart").getContext('2d'), {
        type: 'pie',
        data: {
            labels: c_text,
            datasets: [{
                label: "Polls (Votes)",
                backgroundColor: ["rgba(0,255,255,0.8)","rgba(159,187,182,0.8)","rgba(193,169,147,0.8)","rgba(219,148,114,0.8)","rgba(244,126,82,0.8)",],
                data: c_votes,
            }]
        },
        options: {}
    });
</script>
{% endblock content %}