accounts/urls.py
from django.urls import re_path
from . import views
from django.contrib.auth.views import (
        PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView, LoginView
        )
from django.contrib.auth.models import User
app_name = 'accounts'




urlpatterns = [
        re_path(r'^$', views.home, name="home"),
        re_path(r'^login/$', views.login_view, name="login"),
        re_path(r'^logout/$', views.logout_view, name="logout"),
        re_path(r'^signup/$', views.signup_view, name="signup"),
        re_path(r'^setting/(?P<username>\w+)/$', views.settings_view, name="settings"),
        re_path(r'^delete_confirm/$', views.delete_view, name="delete"),
        re_path(r'^delete/$', views.delete_account, name="delete_account"),
        re_path(r'^signup/details/$', views.signup_detailsview, name="details"),
        re_path(r'^profile/(?P<username>\w+)/$', views.view_profile, name="profile"),
        #re_path(r'^profile/(?P<username>\w+)/$', views.view_other, name="others_profile"),
        re_path(r'^profile/edit/(?P<username>\w+)/$', views.edit_profile, name="edit_profile"),
        re_path(r'^change-password/$', views.change_password, name="change_password"),
        re_path(r'^reset-password/$', PasswordResetView.as_view(template_name='accounts/reset_password.html', email_template_name="accounts/reset_password_email.html", success_url="done/"), name="password_reset"),
        re_path(r'^reset-password/done/$', PasswordResetDoneView.as_view(template_name='accounts/reset_password_done.html'), name="password_reset_done"),
        re_path(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', PasswordResetConfirmView.as_view(template_name="accounts/reset_password_confirm.html"), name="password_reset_confirm"),
        #path('reset/done', PasswordResetCompleteView.as_view(template_name="accounts/reset_password_complete.html"), name="password_reset_complete"),
        re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate, name='activate'),
]

api/urls.py
from django.urls import path,include,re_path
from api import views
from rest_framework.authtoken import views as authviews
urlpatterns = [
    path('userprofile',views.userprofile,name='userprofile'),
    path('testview',views.testview,name='testview'),
    path('interests',views.interests,name='interests'),
    path('friends',views.friends,name='friends'),
    path('friendrequest',views.friendrequest,name='friendrequest'),
    path('message',views.message,name='message'),
    path('forums',views.forums,name='forums'),
    path('topics',views.topics,name='topics'),
    path('posts',views.posts,name='posts'),
    path('polls',views.polls,name='polls'),
    path('vote',views.vote,name='vote'),
    re_path(r'^api-token-auth/', authviews.obtain_auth_token)
]

circlr/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from accounts import views as accounts_views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import PasswordResetCompleteView

urlpatterns = [
	path('reset/done/', PasswordResetCompleteView.as_view(template_name="accounts/reset_password_complete.html"), name="password_reset_complete"),
    path('admin/', admin.site.urls),
	path('api/',include('api.urls')),
    re_path(r'^accounts/', include('accounts.urls', namespace='accounts')),
    re_path(r'^$', accounts_views.home, name="home"),
    path('', include('django.contrib.auth.urls')),
    path('forums/', include('forums.urls')),
	path('friends/', include('friends.urls'), name="friends"),
    path('polls/', include('polls.urls')),
	re_path(r'^files/', include('files.urls')),
    re_path(r'^chat/', include('chat.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.CharField(max_length=255, blank=True, null=True)
    city = models.CharField(max_length=200, blank=True, null=True)
    picture = models.ImageField(upload_to='profile_image', blank=True, default='default_profile.jpeg')

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.userprofile.save()


class Interest_Model(models.Model):
    username = models.ForeignKey(User, on_delete=models.CASCADE, related_name='+')
    interest = models.CharField(max_length=200, default='')

    def __str__(self):
        return str(self.username)



class EmailConfirm(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email_confirmed = models.BooleanField(default=False)

@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        EmailConfirm.objects.create(user=instance)
    instance.emailconfirm.save()

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import UserProfile, Interest_Model
from django.utils.safestring import mark_safe

class RegistrationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        )

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        
        if commit:
            user.save()

        return user

    def clean_email(self):
        data = self.cleaned_data['email']
        if User.objects.filter(email=data).exists():
            raise forms.ValidationError("This email already exists")
        return data


class EditProfileForm(forms.ModelForm):

    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'email',

        )
        #use exclude = () to exclude



class UserProfileForm(forms.ModelForm):
    picture = forms.ImageField(required=False)

    class Meta:
        model = UserProfile
        fields = ('bio', 'city', 'picture')

    def save(self, user=None):
        user_profile = super(UserProfileForm, self).save(commit=False)
        if user:
            user_profile.user = user
        user_profile.save()
        return user_profile

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth import login, logout, authenticate
from accounts.forms import (
    RegistrationForm,
    EditProfileForm
)
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.models import User
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from .models import UserProfile, Interest_Model
from .forms import UserProfileForm
from django.contrib import messages
from django.views.decorators.cache import cache_control
from django.views.generic import UpdateView
from django.urls import reverse
from django.http import HttpResponse
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.core.mail import EmailMessage
from django.http import Http404
import base64


# Create your views here.
@login_required(login_url="/accounts/login")
def home(request):
    return render(request, 'accounts/home.html')




def signup_view(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = True
            user.save()
            current_site = get_current_site(request)
            mail_subject = 'Activate your PeerPair account.'
            message = render_to_string('accounts/acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid' : base64.urlsafe_b64encode(str(user.pk).encode()).decode(),
                'token':account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                        mail_subject, message, to=[to_email]
            )
            email.send()
            return render(request, 'accounts/email_confirm.html')
        else:
            print("Form is not valid")
    else:
        form = RegistrationForm()
    return render(request, 'accounts/signup.html', {'form': form})




def signup_detailsview(request):
    if request.method == 'POST':
        profile_form = UserProfileForm(request.POST, request.FILES, instance=request.user.userprofile)
        if profile_form.is_valid():
            profile_form.save()
            interest_var = request.POST.get('interests')
            interest_var = interest_var.lower().replace(","," ")
            interest_var = interest_var.split()
            for var in interest_var:
                a = User.objects.get(username=request.user.username)
                Interest_Model.objects.create(username=a, interest=var)
            return redirect('accounts:home')
        else:
            messages.error(request, ('Please correct the error below'))
    else:
        profile_form = UserProfileForm(instance=request.user.userprofile)
    return render(request, 'accounts/details.html', {'profile_form': profile_form})






def login_view(request):
     if request.user.is_authenticated:
         return redirect('accounts:home')
     else:
        if request.method == 'POST':
            print("Hi-----------------------------------",request.body)
            form = AuthenticationForm(data=request.POST)
            print("Form is valid or not --------------", form.is_valid)
            if form.is_valid():
                print("Form is Valid----------------")
                user = form.get_user()
                print("User details--------", user)
                login(request, user)
                if 'next' in request.POST:
                    print("inside next-------------")
                    return redirect(request.POST.get('next'))
                else:
                    print("home accounts")
                    return redirect('accounts:home')
            else:
                print("Errors are------",form.errors)
                print("Form is not valid")
        else:
            print("Else--------------------")
            form = AuthenticationForm()
        return render(request, 'accounts/login.html', {'form': form})




def logout_view(request):
    #if request.method == 'POST':
        logout(request)
        return redirect('accounts:home')


@login_required(login_url="/accounts/login")
def settings_view(request, username):
    if request.user == User.objects.get(username=username):
        return render(request, 'accounts/settings.html')
    else:
        raise Http404

@csrf_exempt
@login_required(login_url="/accounts/login")
def delete_account(request):
    confirm = request.POST.get("confirm")
    print(confirm)
    if confirm=="ok":
        print("Confirm is ok")
        u = User.objects.get(username = request.user.username)
        u.delete()
        logout(request)
    return redirect('accounts:home')


@login_required(login_url="/accounts/login")
def delete_view(request):
    return render(request, 'accounts/delete_confirm.html')


@login_required(login_url="/accounts/login")
def view_profile(request, username):
    user = User.objects.get(username=username)
    interests = Interest_Model.objects.filter(username=user)
    editable = False
    if request.user.is_authenticated and request.user == user:
        editable = True
    interestlist=[]
    for i in interests:
        interestlist.append(i.interest)

    args = {'user':user, 'editable':editable, 'interestlist':interestlist}
    return render(request, 'accounts/profile.html', args)





@login_required(login_url="/accounts/login")
def edit_profile(request, username):
    user = User.objects.get(username=username)
    inters = Interest_Model.objects.filter(username=user)
    interest_list=[]
    for i in inters:
        interest_list.append(i.interest)
    if request.user.is_authenticated and request.user == user:
        if request.method == 'POST':
            user_form = EditProfileForm(request.POST, instance=request.user)
            profile_form = UserProfileForm(request.POST, request.FILES, instance=request.user.userprofile)
            if user_form.is_valid() and profile_form.is_valid():
                user_form.save()
                profile_form.save()
                to_delete = Interest_Model.objects.filter(username=user)
                if to_delete.exists():
                    to_delete.delete()
                interest_var = request.POST.get('interests')
                interest_var = interest_var.lower().replace(" ","")
                interest_var = interest_var.lower().replace(","," ").split(" ")
                interest_var = list(filter(None, interest_var))
                for var in interest_var:
                    a = User.objects.get(username=request.user.username)
                    Interest_Model.objects.create(username=a, interest=var)
                messages.success(request, ('Your profile was successfully updated!'))
                return redirect(reverse('accounts:profile', args=[request.user]))
            else:
                messages.error(request, ('Please correct the error below.'))
        else:
            user_form = EditProfileForm(instance=request.user)
            profile_form = UserProfileForm(instance=request.user.userprofile)
        args = {'user_form': user_form, 'profile_form': profile_form, 'interest_list':interest_list}
        return render(request, 'accounts/edit_profile.html', args)



@login_required(login_url="/accounts/login")
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('/accounts')
        else:
            return redirect('/accounts/change-password')
    else:
        form = PasswordChangeForm(user=request.user)
        args = {'form': form}
        return render(request, 'accounts/change_password.html', args)




def activate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None:
        user.is_active = True
        user.emailconfirm.email_confirmed = True
        user.save()
        login(request, user)
        # return redirect('home')
        #return HttpResponse('Thank you for your email confirmation. Now you can login your account.')
        return redirect('accounts:details')
    else:
        return HttpResponse('Activation link is invalid!')

accounts/templates/accounts/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'accounts:activate' uid as uidb64 token as token %}
{% endautoescape %}

accounts/templates/accounts/delete.html
{% extends 'base.html' %}

{% block content %}
      <h1>Thank You for using our website</h1>
      <br><br>
      <div>
        <p>You can <a href="{% url 'accounts:signup' %}">Signup</a> again here</p>
      </div>
{% endblock %}

accounts/templates/accounts/delete_confirm.html
{% extends 'base.html' %}
{% block head %}
<title>
      Confirm Delete
</title>
{% endblock head %}
{% block css %}
{{block.super}}
<style>
      #Submit{
            color: #0083FD;
            background-color: rgb(200, 200, 200);
            transition: all 0.1s ease;
            cursor: pointer;
            width: 45%;
            border-color: #0083FD;
            border-radius: 100px;
            background: none;
            font-family: Sitefont-medium;
            font-size: 15px;
            padding: 7px;
      }
      #Submit:hover{
            color: rgb(200, 200, 200);
            background-color: #0083FD;
            transition: all 0.1s ease;
      }
      #Submit:first-child{
        margin-right: 5px;
      }
</style>
{% endblock css %}
{% block content %}
<div class="sidepad" style="width:33%;margin-top:80px;padding:10px;float: left;"></div>
<div class="sidepad" style="width:33%;margin-top:80px;padding:10px;float: right;"></div>
<div class="centercontent" style="width:34%;max-width:1400px;margin-top:20px;padding:10px;float: right;">
  <h1>Are you sure you want to delete this account?</h1>
  <br><br>
  <div class="row">
    <button id="Submit" onclick="confirmdelete()" style="float:left">Yes, I am sure</button>
    <button id="Submit" onclick="window.location.href='{% url "accounts:settings" user.username %}'" style="float:left">No, go back</button>
  </div>
  <script src="https://cdn.rawgit.com/mgalante/jquery.redirect/master/jquery.redirect.js"></script>
  <script type="text/javascript">
    function confirmdelete() {

      $.redirect('{% url "accounts:delete_account" %}', { 'confirm': 'ok', 'arg2': 'value2' });
    }
  </script>
  {% endblock %}

accounts/templates/accounts/details.html
{% extends 'base_blank.html' %}
{% load crispy_forms_tags %}
{% block head %}
<title>
      Fill in your details
</title>
{% endblock head %}
{% block css %}
{{ block.super }}
<style>
ul li{
  margin-left:0;
}
input[type=text], input[type=password], input[type=email] {
    width: 100%;
    height: 40px;
    font-size: 18px;
    font-family: Sitefont-medium;
    margin: 0px;
    display: block;
    border: none;
    padding: 10px 0;
    border-bottom: solid 1px #0083FD;
    -webkit-transition: all 0.3s cubic-bezier(0.64, 0.09, 0.08, 1);
    transition: all 0.3s cubic-bezier(0.64, 0.09, 0.08, 1);
    background: -webkit-linear-gradient(top, rgba(255, 255, 255, 0) 96%, #0083FD 4%);
    background: linear-gradient(to bottom, rgba(255, 255, 255, 0) 96%, #0083FD 4%);
    background-position: -2000px 0;
    background-repeat: no-repeat;
    color: #0083FD;
}
input[type=text]:focus, input[type=text]:valid, input[type=email]:focus, input[type=email]:valid, input[type=password]:focus, input[type=password]:valid {
    box-shadow: none;
    outline: none;
    background-position: 0 0;
  }
input[type=text]:focus::-webkit-input-placeholder, input[type=text]:valid::-webkit-input-placeholder {
    color: #0083FD;
    font-size: 11px;
    -webkit-transform: translateY(-100px);
            transform: translateY(100px);
    visibility: visible !important;
}
#Submit{
  color: #0083FD;
  background-color: rgb(200, 200, 200);
  transition: all 0.1s ease;
  cursor: pointer;
  width: 50%;
  border-color: #0083FD;
  border-radius: 100px;
  background: none;
  font-family: Sitefont-medium;
  font-size: 15px;
  padding: 7px;
}
#Submit:hover{
  color: rgb(200, 200, 200);
  background-color: #0083FD;
  transition: all 0.1s ease;
}
label{
  font-size: 22px;
}
#div_id_picture{
  font-size: 18px;
  text-align: justify;
  background: rgba(0,0,0, 0.2);
  padding-top:15px ;
  border-radius: 0px 0px 10px 10px;
}
#id_picture {
  width: 70%;
}
#id_picture::-webkit-file-upload-button{
  color: #0083FD;
  background-color: rgb(200, 200, 200);
  transition: all 0.1s ease;
  cursor: pointer;
  border-color: #0083FD;
  border-radius: 100px;
  background: none;
  font-family: Sitefont-medium;
  font-size: 15px;
  padding: 7px;
  width: 125px;
}
</style>
{% endblock css %}
{% block content %}
<div class="sidepad" style="width:33%;margin-top:80px;padding:10px;float: left;"></div>
<div class="sidepad" style="width:33%;margin-top:80px;padding:10px;float: right;"></div>
<div class="centercontent" style="width:34%;max-width:1400px;margin-top:20px;padding:10px;float: right;">
  <h1>Tell Us More About Yourself</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ profile_form|crispy }}<br>
    <label for="Interest">Interests:</label><input type="text" name="interests" value="" id="Interest"><br>
    <center><button type="submit" class="btn-default btn-lg" id = "Submit">Submit</button></center>
  </form>
</div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load crispy_forms_tags %}
{% block head %}
<title>
      Login
</title>
{% endblock head %}
{% block css %}
{{ block.super }}
<style>
  ul li{
  margin-left:0;
}
#Submit{
  color: #0083FD;
  background-color: rgb(200, 200, 200);
  transition: all 0.1s ease;
  cursor: pointer;
  width: 50%;
  border-color: #0083FD;
  border-radius: 100px;
  background: none;
  font-family: Sitefont-medium;
  font-size: 15px;
  padding: 7px;
}
#Submit:hover{
  color: rgb(200, 200, 200);
  background-color: #0083FD;
  transition: all 0.1s ease;
}
label{
  font-size: 22px;
}
</style>
{% endblock css %}
{% block title %}
Login to Circlr
{% endblock title %}
{% block content %}
<div class="sidepad" style="width:33%;margin-top:80px;padding:10px;float: left;"></div>
<div class="sidepad" style="width:33%;margin-top:80px;padding:10px;float: right;"></div>
<div class="centercontent" style="width:34%;max-width:1400px;margin-top:20px;padding:10px;float: right;">
  <h1>Log in</h1>
  <form class="site-form" action="{% url 'accounts:login' %}" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    {% if request.GET.next %}
    <input type="hidden" name="next" value="{{ request.GET.next }}">
    {% endif %}<br>
    <center><input type="submit" value="Login" id="Submit"></center>
  </form>
  <center><p><br>Don't have an account? <a href="{% url 'accounts:signup' %}"> Sign Up </a></p>
  <p><a href="{% url 'accounts:password_reset' %}">Forgot Password?</a></p></center>
</div>
{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'base.html' %}
{% block head %}
<title>
      Logout
</title>
{% endblock head %}
{% block content %}
<div class="sidepad" style="width:33%;margin-top:80px;padding:10px;float: left;"></div>
<div class="sidepad" style="width:33%;margin-top:80px;padding:10px;float: right;"></div>
<div class="centercontent" style="width:34%;max-width:1400px;margin-top:20px;padding:10px;float: right;">
    <h1>Logged out</h1>
    <p>
        You have logged out!
    </p>
    <p>
        <a href="{% url 'accounts:login'%}">Login again?</a>
    </p>
</div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<title>
      Profile
</title>
{% endblock head %}
{% block css %}
{{ block.super }}
<style>
  #propic {
    width: 200px;
    height: 200px;
    border-radius: 100px;
    overflow: hidden;
    background: url("{{ user.userprofile.picture.url }}");
    background-position: center;
    background-size: auto 200px;
    -webkit-user-select: none;
    background-repeat: no-repeat;
    user-select: none;
    margin: auto;
    position: relative;
    top: 50px;
  }

  .circlepro {
    flex: 0 0 500px;
    height: 300px;
    -webkit-user-select: none;
    user-select: none;
    margin-top: 50px;
  }

  .hero-logo-circles {
    width: 300px;
    margin: auto;
    position: relative;
  }

  .hero-logo-circle {
    position: absolute;
    left: 0;
    top: 0;
    animation: hero-logo-circle 1s linear infinite;
    will-change: transform
  }

  p {
    font-size: 18px;
  }

  #bio {
    width: 100%;
    vertical-align: middle;
    text-align: center;
    padding: 10px 5px;
    font-family: Sitefont-book;
    font-size: 15px;
    margin-top: -35px;
    border-radius: 15px;
    margin-bottom: 15px;
  }

  #bio:hover {
    background: rgba(0, 0, 0, 0.07);
    transition: background 1s;
  }

  #editdiv{
    width: 100%;
    text-align: right;
  }

  #edit {
    color: #0083FD;
    background-color: rgb(200, 200, 200);
    transition: all 0.1s ease;
    cursor: pointer;
    border-color: #0083FD;
    border-radius: 100px;
    font-family: Sitefont-medium;
    font-size: 15px;
    padding: 7px;
  }

  #edit:hover {
    color: rgb(200, 200, 200);
    background-color: #0083FD;
    transition: all 0.1s ease;
  }
</style>
{% endblock css %}
{% block content %}
<div class="sidepad" style="width:33%;margin-top:80px;padding:10px;float: left;"></div>
<div class="sidepad" style="width:33%;margin-top:80px;padding:10px;float: right;"></div>
<div class="centercontent" style="width:34%;padding:10px;float: right;">
  <div class="circlepro">
    <div class="hero-logo-circles">
      <img class="hero-logo-circle" src="{% static 'svgs/index-portal-green-semi.svg' %}" alt="Index portal green semi">
      <img class="hero-logo-circle" src="{% static 'svgs/index-portal-green.svg' %}" alt="Index portal green">
      <img class="hero-logo-circle" src="{% static 'svgs/index-portal-orange-semi.svg' %}" alt="Index portal orange semi">
      <img class="hero-logo-circle" src="{% static 'svgs/index-portal-orange.svg' %}" alt="Index portal orange">
      <img class="hero-logo-circle" src="{% static 'svgs/index-portal-blue-semi.svg' %}" alt="Index portal blue semi">
      <img class="hero-logo-circle" src="{% static 'svgs/index-portal-blue.svg' %}" alt="Index portal blue">
      <img class="hero-logo-circle" src="{% static 'svgs/index-portal-red-semi.svg' %}" alt="Index portal red semi">
      <img class="hero-logo-circle" src="{% static 'svgs/index-portal-red.svg' %}" alt="Index portal red">
      <img class="hero-logo-circle" src="{% static 'svgs/index-portal-yellow-semi.svg' %}" alt="Index portal yellow semi">
      <img class="hero-logo-circle" src="{% static 'svgs/index-portal-yellow.svg' %}" alt="Index portal yellow">
      <div id="propic"></div><br>
    </div>
  </div>
  <center>
    <p style="font-size:36px; margin-top:0px;font-family: Sitefont-medium">{{ user }}<br></p>
    {% if user.userprofile.bio %}<div id="bio">{{ user.userprofile.bio }}</div>{% endif %}
  </center>
  <div id="editdiv">
    {% if editable == True %}
    <button id="edit" onclick="window.location.href='{% url 'accounts:settings' user.username %}'">Settings</button>
    <button id="edit" onclick="window.location.href='{% url 'accounts:edit_profile' user.username %}'">Edit Profile</button>
    {% endif %}
  </div>
  </p>
  <p>Name: {{ user.first_name }} {{ user.last_name }}</p>
  <p>Email: {{ user.email }} </p>
  <p>City: {{ user.userprofile.city }} </p>
  <p id="interest">Interests:
                {% for int in interestlist %}
                {{int}},
                {% endfor %}</p>
</div>
{% endblock %}

accounts/templates/accounts/settings.html
{% extends 'base.html' %}
{% block head %}
<title>
      Settings
</title>
{% endblock head %}
{% block css %}
{{block.super}}
<style>
      #Submit{
            color: #0083FD;
            background-color: rgb(200, 200, 200);
            transition: all 0.1s ease;
            cursor: pointer;
            width: 50%;
            border-color: #0083FD;
            border-radius: 100px;
            background: none;
            font-family: Sitefont-medium;
            font-size: 15px;
            padding: 7px;
            margin-bottom: 20px;
      }
      #Submit:hover{
            color: rgb(200, 200, 200);
            background-color: #0083FD;
            transition: all 0.1s ease;
      }
      h1{
          font-size: 50px;
      }
</style>
{% endblock css %}
{% block content %}
<div class="sidepad" style="width:33%;margin-top:80px;padding:10px;float: left;"></div>
<div class="sidepad" style="width:33%;margin-top:80px;padding:10px;float: right;"></div>
<div class="centercontent" style="width:34%;max-width:1400px;margin-top:50px;padding:10px;float: right;">
    <center>
    <h1>Profile settings</h1>
    <br><br>
    <div class="row">
        <button id="Submit" onclick="window.location.href='{% url "accounts:change_password" %}'">Change Password</button>
        <button id="Submit" onclick="window.location.href='{% url "accounts:delete" %}'">Delete Your Account</button>
        <button id="Submit" onclick="window.location.href='{% url "accounts:profile" request.user.username %}'">Go Back</button>
    </div>
    </center>
</div>
{% endblock %}